Repository cloudposse/terraform-aws-documentdb-cluster, pull requests merged in 2025-05, with the labels that each got.

#117 feat: consolidate enable parameters to locals and fix invalid count bug
  main.tf
Labels: patch, bugfix

#118 fix: address invalid count bug
  main.tf
  variables.tf
Labels: minor

#121 Replace Makefile with atmos.yaml
  Makefile
  README.yaml
  atmos.yaml
  docs/targets.md
  docs/terraform.md
Labels: auto-update, no-release, migration
